### ISSUE TITLE
Score produced by NYC Taxi 4 - Custom Featuretools Primitives

### ISSUE THREAD

**Issue by htcml** [Featuretools/NYC-Taxi-Demo#7]
The notebook states the following performance results:
Received a score of 0.39256 on the Kaggle competition.
    Placed 416 out of 1257.
    Beat 67% of competitors on the Kaggle competition.
    Had a modeling RMSE of 0.33454

I ran multiple times and only can get the score of 0.42889, which is far higher than 0.39256. Could you please check? This score is not much different from those of Tax 3 notebook.

**Comment by thehomebrewnerd** [comment]
@htcml I can't speak directly to why the scores are different. However, a lot has changes in Featuretools and I presume XGB, since this notebook was originally created in 2017. These changes could be responsible for the differences, but there might be other factors as well. I'm simply not sure.

Having said that, the point of these notebooks is mainly to demonstrate how to use Featuretools to streamline the feature creation process for various types of problems, and also how you can create custom primitives that *might* be beneficial to a specific problem. This is certainly not to say that the features that result from custom primitives will always improve model predictions...they might, or they might have little to no impact.

These notebooks are best used to understand the process for using Featuretools, but not so much for recreating specific prediction results.

**Comment by htcml** [comment]
Thanks for clarification!
