### ISSUE TITLE
Why a vendor_id is associated with several different vendors.COUNT(trips)?

### ISSUE THREAD

**Issue by htcml** [Featuretools/NYC-Taxi-Demo#8]
This question is for NYC Taxi 3 - Simple Featuretools.

I run this command:
```
feature_matrix.groupby(['vendor_id','vendors.COUNT(trips)']).size()
```
get the following output. Can you explain how FT comes up with these different counts for each vendor_id? Or this is a bug with FT?
```
vendor_id  vendors.COUNT(trips)
1          0                        52301
           52301                   181675
           233976                  196150
           430126                  195433
           625559                  191159
           816718                  138047
2          0                        61152
           61152                   211531
           272683                  226281
           498964                  223220
           722184                  217368
           939552                  155949
```

**Comment by thehomebrewnerd** [comment]
The reason you are getting multiple trip counts for a single `vendor_id` is because of the cutoff times that are being supplied to `dfs`. In short, by passing the cutoff time dataframe, we are telling `dfs` to calculate features at multiple points in time.

If you remove the cutoff time parameter from `dfs`, the current time will be used as a single cutoff time, and you will see a single COUNT returned for each vendor.

[More on cutoff times from the Featuretools docs](https://docs.featuretools.com/en/stable/automated_feature_engineering/handling_time.html#what-is-the-cutoff-time)

**Comment by htcml** [comment]
Thanks for explanation!
